train:
  data_dir: ../datasets/Mobile_Price/
  out_dir: ../output/Mobile_Price/
  dataset_name: "Mobile_Price"
  target: "price_range"
  models:
    - name: "LogisticRegression"
      params_range:
        C: [0.1, 0.5, 10.0]
        max_iter: [30, 50, 300]
    - name: "RandomForest"
      params_range:
        n_estimators: [100, 200, 300]
        max_depth: [5, 10, 15]
    - name: "DecisionTree"
      params_range:
        max_depth: [5, 10, 15]