train:
  data_dir: ../datasets/Bank_Churn/
  out_dir: ../output/Bank_Churn/
  target: "Exited"
  models:
    - name: "LogisticRegression"
      params_range:
        C: [0.1, 1.0, 10.0]
        max_iter: [100, 200, 300]
    - name: "RandomForestClassifier"
      params_range:
        n_estimators: [100, 200, 300]
        max_depth: [5, 10, 15]
    - name: "DecisionTreeClassifier"
      params_range:
        max_depth: [5, 10, 15]
    - name: "GradientBoostingClassifier"
      params_range:
        n_estimators: [100, 200, 300]
        max_depth: [5, 10, 15]